# This is a basic workflow to help you get started with Actions

name: demo CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    paths-ignore:
    - 'docs/**'

  pull_request:
    branches: [ main ]
    paths-ignore:
    - 'docs/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
  # Also trigger on page_build, as well as release created events
  page_build:
  
  release:
    types: # This configuration does not affect the page_build event above
      - created
      
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  checkpatch:
    runs-on: ubuntu-latest
    
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Check out repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 100

      - name: Check out another repo
        uses: actions/checkout@v2
        with:
          repository: krzycz/demo
          path: ./src/INCLUDE
          fetch-depth: 100
          ref: ${{ github.ref }}

      - name: Check commit message
        run: make check-commit-msg
    
      - name: Check coding style
        run: make cstyle

  # This workflow contains a single job called "build"
  build:
    needs: checkpatch
  
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
         - xxx: 1
           debug: 1
         - xxx: 0
           debug: 1
         - xxx: 1
           debug: 0

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Check out repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 100

      - name: Check out another repo
        uses: actions/checkout@v2
        with:
          repository: krzycz/demo
          path: ./src/INCLUDE
          fetch-depth: 100
          ref: ${{ github.ref }}

      # Runs a single command using the runners shell
      - name: Build it
        run: make all DEBUG=${{ matrix.debug }} XXX=${{ matrix.xxx }}

      # Runs a set of commands using the runners shell
      - name: Run some tests
        run: make check
 
