name: manual

on:
  push:
    branches:
      - main
      - release

 #schedule:
 #   # every day at 01:00am
 #   - cron: '0 1 * * *'

  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
      tags:
        description: 'Test scenario tags'
        required: false
        type: boolean
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  xxx:
    runs-on: ubuntu-latest
    env:
      BRANCH: ${{ github.ref }}
    steps:
      - run: |
          echo "Log level: $LEVEL"
          echo "Tags: $TAGS"
          echo "BRANCH: $BRANCH"
          echo "REF: $GITHUB_REF"
        env:
          LEVEL: ${{ inputs.logLevel }}
          TAGS: ${{ inputs.tags }}

  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
         - xxx: 1
           debug: 1
         - xxx: 0
           debug: 1
         - xxx: 1
           debug: 0

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Check out repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 100

      # Runs a single command using the runners shell
      - name: Build it
        run: make all DEBUG=${{ matrix.debug }} XXX=${{ matrix.xxx }}

