# This is a basic workflow to help you get started with Actions

name: demo release

# Controls when the action will run. 
on:
  release:
      
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  package:
    runs-on: ubuntu-latest
    
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Create a tarball
        run: tar czf demo.tgz *
    
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: demo.tgz
          asset_name: tarball
          tag: ${{ github.ref }}
          overwrite: true
          body: "This is my release text"
      
      - name: Upload Release Asset 2
        uses: AButler/upload-release-assets@v2.0
        with:
          files: '*.tgz'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          release-tag: ${{ github.ref }}
