name: reuse

on:
  workflow_call:
    inputs:
      param1:
        required: true
        type: string
    
  workflow_dispatch:
    inputs:
      param1:
        required: true
        type: string
  
  pull_request:
  
jobs:
  build:
    uses: krzycz/demo/.github/workflows/test.yml@main
    with:
      param1: ${{ inputs.param1 }}

  build2:
    if: github.repository == 'krzycz/demo2'
    uses: krzycz/demo/.github/workflows/test.yml@main
    with:
      param1: 'foobar'
