name: reuse

on:
  workflow_call:
    inputs:
      param1:
        required: true
        type: string
    
  workflow_dispatch:
    inputs:
      param1:
        required: true
        type: string
    
jobs:
  build:
    uses: krzycz/demo/.github/workflows/test.yml@main
    with:
      param1: ${{ inputs.param1 }}
