name: triggered remotely

on:
  workflow_dispatch:
    inputs:
      param1:
        required: true
        type: string
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Build it
        run: |
          echo "ref: ${{ github.ref }}"
          echo "workflow: ${{ github.workflow }}"
          echo "param1: ${{ inputs.param1 }}"
          echo "repo: ${{ github.event.workflow_dispatch.repository.full_name }}"        
          echo "sender: ${{ github.event.workflow_dispatch.sender.login }}"        
          echo "workflow: ${{ github.event.workflow_dispatch.workflow }}"
          echo "ref: ${{ github.event.workflow_dispatch.ref }}"

